/* Default question library for Miles (age ~5.5, reads English, loves science /
   trick-shots / MrBeast / Bluey / Numberblocks). Parents can edit everything
   from the in-app editor; "Reset to defaults" re-loads this file. */
window.SEED = {
  packs: [
    /* lang groups the home screen: 'zh' cards look different from 'en' cards
       so a pre-reader can tell Chinese games from English ones at a glance */
    { id: 'zh-quest',  name: 'Character Quest 認字', emoji: '🐉', color: 'a4', generated: true, lang: 'zh' },
    { id: 'zh-words',  name: 'Word Quest 詞語', emoji: '🐼', color: 'a5', generated: true, lang: 'zh' },
    { id: 'zh-sentences', name: 'Silly Sentences 短句', emoji: '😜', color: 'a2', generated: true, lang: 'zh' },
    { id: 'zh-write',  name: 'Write Quest 寫字', emoji: '✍️', color: 'a0', generated: true, lang: 'zh' },
    { id: 'zh-build',  name: 'Character Builder 拼字', emoji: '🧩', color: 'a1', generated: true, lang: 'zh' },
    { id: 'zh-whack',  name: 'Whack-a-Char 打地鼠', emoji: '🔨', color: 'a3', generated: true, lang: 'zh' },
    { id: 'zh-twins',  name: 'Spot the Twin 找雙胞胎', emoji: '👯', color: 'a6', generated: true, lang: 'zh' },
    { id: 'zh-match',  name: 'Memory Match 翻牌配對', emoji: '🃏', color: 'a4', generated: true, lang: 'zh' },
    { id: 'zh-bingo',  name: 'Bingo 賓果', emoji: '🎱', color: 'a2', generated: true, lang: 'zh' },
    { id: 'zh-order',  name: 'Sentence Builder 造句', emoji: '🧱', color: 'a5', generated: true, lang: 'zh' },
    { id: 'zh-morph',  name: 'Ancient Pictures 象形變身', emoji: '🏺', color: 'a1', generated: true, lang: 'zh' },
    { id: 'zh-flash',  name: 'Flash Write 閃字記憶', emoji: '⚡', color: 'a0', generated: true, lang: 'zh' },
    { id: 'zh-hunt',   name: 'Hide & Seek 找字', emoji: '🔍', color: 'a3', generated: true, lang: 'zh' },
    { id: 'zh-count',  name: 'Count & Say 數一數', emoji: '🔢', color: 'a6', generated: true, lang: 'zh' },
    { id: 'zh-opposites', name: 'Opposites 相反詞', emoji: '↔️', color: 'a4', generated: true, lang: 'zh' },
    { id: 'zh-garden', name: 'Character Garden 字的花園', emoji: '🌱', color: 'a3', generated: true, lang: 'zh' },
    { id: 'math-machine', name: 'Math Machine', emoji: '🤖', color: 'a1', generated: true, lang: 'en' },
    { id: 'science',   name: 'Science Lab',     emoji: '🔬', color: 'a3', lang: 'en' },
    { id: 'english',   name: 'Word Power',      emoji: '📖', color: 'a4', lang: 'en' },
    { id: 'world',     name: 'Cool Facts',      emoji: '🌍', color: 'a5', lang: 'en' }
  ],
  /* default packs that were retired — load() removes them from devices
     that still carry them */
  removedPacks: ['cartoons', 'challenge', 'dinos', 'chinese'],
  questions: [
    /* ---------------- SCIENCE LAB (Mark Rober vibes) ---------------- */
    { packId:'science', type:'mc', emoji:'🪐', text:'What planet do we live on?',
      options:['Earth','Mars','The Moon','The Sun'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'🧊', text:'Ice is frozen...?',
      options:['Water','Milk','Air','Sand'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'🌱', text:'What do plants need to grow big?',
      options:['Sunlight and water','Pizza','Toys','Darkness'], correct:0, time:30, level:1 },
    { packId:'science', type:'tf', emoji:'🧲', text:'A magnet can stick to metal.',
      options:['True','False'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'🌈', text:'A rainbow is made when sunlight shines through...?',
      options:['Rain drops','Rocks','Fire','Snow'], correct:0, time:30, level:2 },
    { packId:'science', type:'mc', emoji:'🚀', text:'What do we call a person who flies to space?',
      options:['Astronaut','Doctor','Farmer','Chef'], correct:0, time:30, level:2 },
    { packId:'science', type:'tf', emoji:'🦕', text:'Dinosaurs are still alive today.',
      options:['True','False'], correct:1, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'💧', text:'Which one is a liquid?',
      options:['Juice','A rock','A spoon','A book'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'🌡️', text:'When water gets very hot it turns into...?',
      options:['Steam','Ice','Wood','Glass'], correct:0, time:30, level:2 },
    { packId:'science', type:'mc', emoji:'🐝', text:'Bees help flowers by carrying...?',
      options:['Pollen','Water','Rocks','Honey jars'], correct:0, time:30, level:3 },
    { packId:'science', type:'tf', emoji:'🌙', text:'The Moon makes its own light like the Sun.',
      options:['True','False'], correct:1, time:30, level:3 },
    { packId:'science', type:'mc', emoji:'🦋', text:'A caterpillar grows up to become a...?',
      options:['Butterfly','Spider','Fish','Bird'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'🐸', text:'What do we call a baby frog?',
      options:['Tadpole','Puppy','Chick','Kitten'], correct:0, time:30, level:2 },
    { packId:'science', type:'mc', emoji:'🌳', text:'Trees help us by making the air...?',
      options:['Fresh to breathe','Dirty','Hot','Loud'], correct:0, time:30, level:2 },
    { packId:'science', type:'mc', emoji:'🌬️', text:'What do we call moving air?',
      options:['Wind','Rain','Snow','Sand'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'❤️', text:'Which part of your body pumps blood?',
      options:['Heart','Hair','Teeth','Toes'], correct:0, time:30, level:2 },
    { packId:'science', type:'mc', emoji:'🦴', text:'What helps your body stand up tall and strong?',
      options:['Bones','Bubbles','Clouds','Paper'], correct:0, time:30, level:2 },
    { packId:'science', type:'tf', emoji:'☀️', text:'The Sun is very, very hot.',
      options:['True','False'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'🌧️', text:'Water that falls from the clouds is called...?',
      options:['Rain','Glass','Wood','Sand'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'☁️', text:'Clouds up in the sky are made of...?',
      options:['Tiny water drops','Cotton','Smoke','Marshmallows'], correct:0, time:30, level:3 },
    { packId:'science', type:'mc', emoji:'🎨', text:'If you mix red and yellow paint, what colour do you get?',
      options:['Orange','Green','Black','Blue'], correct:0, time:30, level:2 },
    { packId:'science', type:'mc', emoji:'🐜', text:'How many legs does an insect like an ant have?',
      options:['6','4','8','2'], correct:0, time:30, level:3 },
    { packId:'science', type:'mc', emoji:'🪶', text:'Which one floats down more slowly, a feather or a rock?',
      options:['A feather','A rock','Both the same','Neither'], correct:0, time:30, level:2 },
    { packId:'science', type:'mc', emoji:'🌋', text:'What hot, runny stuff comes out of a volcano?',
      options:['Lava','Ice','Juice','Sand'], correct:0, time:30, level:2 },
    { packId:'science', type:'mc', emoji:'🐦', text:"What covers a bird's body?",
      options:['Feathers','Scales','Fur only','Leaves'], correct:0, time:30, level:1 },
    { packId:'science', type:'tf', emoji:'🌍', text:'The Earth is shaped like a giant ball.',
      options:['True','False'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'🐟', text:'How do fish breathe under the water?',
      options:['With their gills','With a nose','With their ears','They hold their breath'], correct:0, time:30, level:2 },
    { packId:'science', type:'mc', emoji:'🦷', text:'What should you do to keep your teeth strong and healthy?',
      options:['Brush them every day','Eat only candy','Never drink water','Chew on rocks'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'🧠', text:'Which body part helps you think and remember things?',
      options:['Brain','Elbow','Knee','Heel'], correct:0, time:30, level:2 },
    { packId:'science', type:'mc', emoji:'👃', text:'Which part of your body do you use to smell?',
      options:['Nose','Ear','Knee','Foot'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'👂', text:'Which part of your body do you use to hear sounds?',
      options:['Ears','Eyes','Nose','Toes'], correct:0, time:30, level:1 },
    { packId:'science', type:'tf', emoji:'🌞', text:'Plants use sunlight to make their own food.',
      options:['True','False'], correct:0, time:30, level:3 },
    { packId:'science', type:'mc', emoji:'⚡', text:'What makes our lights and TV turn on?',
      options:['Electricity','Mud','Leaves','Snow'], correct:0, time:30, level:2 },
    { packId:'science', type:'mc', emoji:'🌊', text:'What do we call the water that rolls up and down at the beach?',
      options:['Waves','Hills','Rocks','Clouds'], correct:0, time:30, level:2 },
    { packId:'science', type:'mc', emoji:'🪨', text:'Which one of these is a solid?',
      options:['A rock','Juice','Steam','Wind'], correct:0, time:30, level:2 },
    { packId:'science', type:'tf', emoji:'💨', text:'We need to breathe air to stay alive.',
      options:['True','False'], correct:0, time:30, level:1 },
    { packId:'science', type:'tf', emoji:'❄️', text:'Ice is colder than warm water.',
      options:['True','False'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'🐣', text:'Which baby animal hatches out of an egg?',
      options:['A chick','A puppy','A kitten','A foal'], correct:0, time:30, level:2 },
    { packId:'science', type:'mc', emoji:'👅', text:'Which part of your body do you use to taste?',
      options:['Tongue','Knee','Elbow','Hair'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'👀', text:'Which part of your body do you use to see?',
      options:['Eyes','Ears','Nose','Feet'], correct:0, time:30, level:1 },
    { packId:'science', type:'tf', emoji:'🌝', text:'The Sun gives us light during the daytime.',
      options:['True','False'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'🧊', text:'If you put water in the freezer, it turns into...?',
      options:['Ice','Steam','Smoke','Rock'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'🌱', text:'Most plants grow from a tiny...?',
      options:['Seed','Rock','Spoon','Cloud'], correct:0, time:30, level:2 },
    { packId:'science', type:'mc', emoji:'🔦', text:'What do you need to see in a dark room?',
      options:['Light','More dark','Water','Noise'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'🔥', text:'What does fire give out?',
      options:['Heat and light','Ice','Snow','Water'], correct:0, time:30, level:2 },
    { packId:'science', type:'mc', emoji:'🐌', text:'A snail moves very...?',
      options:['Slowly','Fast like a rocket','By flying','By jumping'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'🪱', text:'Where does a worm like to live?',
      options:['In the soil','In the sky','In fire','In space'], correct:0, time:30, level:2 },
    { packId:'science', type:'mc', emoji:'🌜', text:'When we can see the Moon and the stars, what time is it?',
      options:['Night time','Lunch time','Morning','Noon'], correct:0, time:30, level:1 },
    { packId:'science', type:'tf', emoji:'🌡️', text:'A thermometer tells us how hot or cold something is.',
      options:['True','False'], correct:0, time:30, level:3 },
    { packId:'science', type:'mc', emoji:'🧼', text:'Soap helps wash away...?',
      options:['Germs and dirt','Sunshine','Music','Numbers'], correct:0, time:30, level:2 },
    { packId:'science', type:'tf', emoji:'🦎', text:'A lizard has dry, scaly skin.',
      options:['True','False'], correct:0, time:30, level:3 },
    { packId:'science', type:'mc', emoji:'🐚', text:'Where would you find a seashell?',
      options:['At the beach','In space','In a volcano','In the fridge'], correct:0, time:30, level:1 },
    { packId:'science', type:'mc', emoji:'🦵', text:'How many legs does a person have?',
      options:['2','4','6','8'], correct:0, time:30, level:1 },

    /* ---------------- WORD POWER (English) ---------------- */
    { packId:'english', type:'mc', emoji:'🅱️', text:'Which word starts with the letter B?',
      options:['Ball','Cat','Dog','Egg'], correct:0, time:30, level:1 },
    { packId:'english', type:'mc', emoji:'🐱', text:'Which word rhymes with CAT?',
      options:['Hat','Dog','Sun','Cup'], correct:0, time:30, level:1 },
    { packId:'english', type:'mc', emoji:'🔤', text:'How many letters are in the word "FROG"?',
      options:['4','3','5','2'], correct:0, time:30, level:1 },
    { packId:'english', type:'mc', emoji:'🍎', text:'A, B, C, D, ... what letter comes next?',
      options:['E','F','G','Z'], correct:0, time:30, level:1 },
    { packId:'english', type:'mc', emoji:'🐶', text:'Which one is an animal?',
      options:['Tiger','Table','Truck','Tree'], correct:0, time:30, level:2 },
    { packId:'english', type:'mc', emoji:'🎨', text:'Which word means "happy"?',
      options:['Glad','Sad','Tired','Angry'], correct:0, time:30, level:2 },
    { packId:'english', type:'mc', emoji:'☀️', text:'What is the opposite of "big"?',
      options:['Small','Tall','Fast','Loud'], correct:0, time:30, level:2 },
    { packId:'english', type:'mc', emoji:'🐍', text:'Which word starts with the same sound as "snake"?',
      options:['Sun','Moon','Apple','Box'], correct:0, time:30, level:3 },
    { packId:'english', type:'tf', emoji:'📚', text:'The word "BLUE" is a colour.',
      options:['True','False'], correct:0, time:30, level:1 },
    { packId:'english', type:'mc', emoji:'🧊', text:'What is the opposite of "hot"?',
      options:['Cold','Big','Fast','Loud'], correct:0, time:30, level:2 },
    { packId:'english', type:'mc', emoji:'🥤', text:'Which word starts with the letter C?',
      options:['Cup','Apple','Dog','Egg'], correct:0, time:30, level:1 },
    { packId:'english', type:'mc', emoji:'🌳', text:'Which word rhymes with "BEE"?',
      options:['Tree','Dog','Hat','Cup'], correct:0, time:30, level:2 },
    { packId:'english', type:'mc', emoji:'⬇️', text:'What is the opposite of "up"?',
      options:['Down','Left','Big','Fast'], correct:0, time:30, level:1 },
    { packId:'english', type:'mc', emoji:'🔢', text:'How many letters are in the word "SUN"?',
      options:['3','2','4','5'], correct:0, time:30, level:1 },
    { packId:'english', type:'tf', emoji:'🐾', text:'The words "DOG" and "CAT" both name animals.',
      options:['True','False'], correct:0, time:30, level:1 },
    { packId:'english', type:'mc', emoji:'🍏', text:'Which word starts with the letter A?',
      options:['Apple','Dog','Cup','Sun'], correct:0, time:30, level:1 },
    { packId:'english', type:'mc', emoji:'🐸', text:'Which word rhymes with "DOG"?',
      options:['Frog','Cat','Sun','Cup'], correct:0, time:30, level:2 },
    { packId:'english', type:'mc', emoji:'🌙', text:'What is the opposite of "day"?',
      options:['Night','Run','Big','Wet'], correct:0, time:30, level:2 },
    { packId:'english', type:'mc', emoji:'🤫', text:'What is the opposite of "loud"?',
      options:['Quiet','Tall','Hot','Fast'], correct:0, time:30, level:2 },
    { packId:'english', type:'mc', emoji:'🔟', text:'How many letters are in the word "TEN"?',
      options:['3','2','4','5'], correct:0, time:30, level:1 },
    { packId:'english', type:'mc', emoji:'📏', text:'Which word means the same as "big"?',
      options:['Large','Tiny','Slow','Cold'], correct:0, time:30, level:3 },
    { packId:'english', type:'mc', emoji:'🔴', text:'Which word is a colour?',
      options:['Red','Run','Jump','Apple'], correct:0, time:30, level:1 },
    { packId:'english', type:'mc', emoji:'🔤', text:'M, N, O, ... what letter comes next?',
      options:['P','Q','A','Z'], correct:0, time:30, level:2 },
    { packId:'english', type:'mc', emoji:'🦊', text:'Which word starts with the letter F?',
      options:['Fox','Dog','Cat','Pig'], correct:0, time:30, level:1 },
    { packId:'english', type:'mc', emoji:'🛑', text:'What is the opposite of "go"?',
      options:['Stop','Jump','Sing','Eat'], correct:0, time:30, level:1 },

    /* ---------------- COOL FACTS (world) ---------------- */
    { packId:'world', type:'mc', emoji:'🐘', text:'Which animal is the biggest?',
      options:['Elephant','Mouse','Ant','Cat'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🦒', text:'Which animal has a very long neck?',
      options:['Giraffe','Pig','Duck','Frog'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🌊', text:'What is the ocean full of?',
      options:['Salt water','Juice','Sand only','Milk'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🍯', text:'Which animal makes honey?',
      options:['Bees','Cows','Dogs','Sharks'], correct:0, time:30, level:1 },
    { packId:'world', type:'tf', emoji:'🐧', text:'Penguins can fly in the sky.',
      options:['True','False'], correct:1, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🚦', text:'On a traffic light, what colour means "GO"?',
      options:['Green','Red','Yellow','Blue'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'❄️', text:'In which season does it snow?',
      options:['Winter','Summer','Spring','None'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🐆', text:'Which animal is the fastest runner on land?',
      options:['Cheetah','Turtle','Snail','Pig'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🐢', text:'Which animal carries its home on its back?',
      options:['Turtle','Dog','Horse','Fish'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🦘', text:'Which animal hops and carries its baby in a pouch?',
      options:['Kangaroo','Cow','Duck','Cat'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🐙', text:'How many arms does an octopus have?',
      options:['8','2','4','6'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🦁', text:'Which animal is called the "King of the Jungle"?',
      options:['Lion','Rabbit','Mouse','Frog'], correct:0, time:30, level:1 },
    { packId:'world', type:'tf', emoji:'🐳', text:'The blue whale is the biggest animal in the world.',
      options:['True','False'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🍌', text:'What do monkeys love to eat?',
      options:['Bananas','Rocks','Shoes','Paper'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🐪', text:'Which animal can travel a long way across the hot desert?',
      options:['Camel','Penguin','Polar bear','Seal'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🦉', text:'Which bird is awake at night and says "hoo"?',
      options:['Owl','Chicken','Duck','Parrot'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'⭐', text:'What twinkles in the sky at night?',
      options:['Stars','Cars','Shoes','Rocks'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🌵', text:'A spiky cactus grows in a hot, dry place called the...?',
      options:['Desert','Ocean','Snow','City'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🍂', text:'In which season do leaves turn brown and fall down?',
      options:['Autumn','Summer','Winter','Spring'], correct:0, time:30, level:3 },
    { packId:'world', type:'mc', emoji:'🐊', text:'Which animal has big sharp teeth and lives in rivers?',
      options:['Crocodile','Sheep','Bunny','Goat'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🌻', text:'A sunflower likes to turn and face the...?',
      options:['Sun','Moon','Ground','Wall'], correct:0, time:30, level:2 },
    { packId:'world', type:'tf', emoji:'🐜', text:'An ant can lift things much bigger than itself.',
      options:['True','False'], correct:0, time:30, level:3 },
    { packId:'world', type:'mc', emoji:'🐘', text:'Which animal has a long trunk on its face?',
      options:['Elephant','Rabbit','Fish','Bird'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🦓', text:'Which animal looks like a horse with black-and-white stripes?',
      options:['Zebra','Cow','Pig','Sheep'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🐼', text:'Which black-and-white animal loves to munch bamboo?',
      options:['Panda','Lion','Shark','Owl'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🦈', text:'Which big sea animal has rows of sharp teeth?',
      options:['Shark','Cow','Sheep','Chicken'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🐮', text:'Which farm animal gives us milk?',
      options:['Cow','Chicken','Sheep','Horse'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🐓', text:'Which animal says "cock-a-doodle-doo" in the morning?',
      options:['Rooster','Cow','Cat','Frog'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🐑', text:'What do we get from a sheep to make warm sweaters?',
      options:['Wool','Milk','Eggs','Honey'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🐍', text:'Which animal is long, has no legs, and slithers on the ground?',
      options:['Snake','Dog','Bird','Cat'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🐻', text:'Which big furry animal sleeps all winter long?',
      options:['Bear','Bee','Fish','Duck'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🦜', text:'Which colourful bird can copy words and "talk"?',
      options:['Parrot','Owl','Penguin','Crow'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🕷️', text:'How many legs does a spider have?',
      options:['8','6','4','2'], correct:0, time:30, level:3 },
    { packId:'world', type:'tf', emoji:'🌎', text:'Most of the Earth is covered by water.',
      options:['True','False'], correct:0, time:30, level:3 },
    { packId:'world', type:'mc', emoji:'🐧', text:'Where do penguins love to live?',
      options:['Cold, icy places','Hot deserts','In trees','In volcanoes'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🦋', text:'Which insect has big, colourful wings?',
      options:['Butterfly','Ant','Worm','Snail'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🐸', text:'Which animal goes "ribbit" and hops near ponds?',
      options:['Frog','Cow','Horse','Bird'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🐬', text:'Which clever sea animal loves to leap out of the water?',
      options:['Dolphin','Cow','Chicken','Spider'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🦅', text:'Which bird flies high and has very sharp eyes?',
      options:['Eagle','Penguin','Chicken','Duck'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🐰', text:'Which animal has long ears and likes to hop?',
      options:['Rabbit','Fish','Snake','Cow'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🐷', text:'Which farm animal says "oink"?',
      options:['Pig','Sheep','Horse','Duck'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🐴', text:'Which animal can you ride and says "neigh"?',
      options:['Horse','Fish','Frog','Bee'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🦆', text:'Which animal says "quack" and loves the water?',
      options:['Duck','Lion','Tiger','Camel'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🐯', text:'Which big cat has orange fur with black stripes?',
      options:['Tiger','Panda','Zebra','Sheep'], correct:0, time:30, level:2 },
    { packId:'world', type:'mc', emoji:'🏔️', text:'What do we call a very, very tall hill?',
      options:['Mountain','Puddle','Beach','Cave'], correct:0, time:30, level:2 },
    { packId:'world', type:'tf', emoji:'🌙', text:'We can sometimes see the Moon in the night sky.',
      options:['True','False'], correct:0, time:30, level:1 },
    { packId:'world', type:'mc', emoji:'🦔', text:'Which small animal is covered in spikes?',
      options:['Hedgehog','Rabbit','Duck','Cow'], correct:0, time:30, level:3 },
    { packId:'world', type:'mc', emoji:'🌴', text:'Tall trees with coconuts that grow where it is hot are...?',
      options:['Palm trees','Pine trees','Cactus plants','Bushes'], correct:0, time:30, level:3 }
  ]
};
