/* Default question library for Miles (age ~5.5, reads English, loves science /
   trick-shots / MrBeast / Bluey / Numberblocks). Parents can edit everything
   from the in-app editor; "Reset to defaults" re-loads this file. */
window.SEED = {
  packs: [
    { id: 'math-machine', name: 'Math Machine', emoji: '🤖', color: 'a1', generated: true },
    { id: 'science',   name: 'Science Lab',     emoji: '🔬', color: 'a3' },
    { id: 'english',   name: 'Word Power',      emoji: '📖', color: 'a1' },
    { id: 'cartoons',  name: 'Cartoon Heroes',  emoji: '📺', color: 'a2' },
    { id: 'challenge', name: 'Beast Challenge',  emoji: '🏆', color: 'a0' },
    { id: 'world',     name: 'Cool Facts',      emoji: '🌍', color: 'a3' },
    { id: 'chinese',   name: 'First Chinese 中文', emoji: '🀄', color: 'a2' }
  ],
  questions: [
    /* ---------------- SCIENCE LAB (Mark Rober vibes) ---------------- */
    { packId:'science', type:'mc', emoji:'🪐', text:'What planet do we live on?',
      options:['Earth','Mars','The Moon','The Sun'], correct:0, time:20, level:1 },
    { packId:'science', type:'mc', emoji:'🧊', text:'Ice is frozen...?',
      options:['Water','Milk','Air','Sand'], correct:0, time:20, level:1 },
    { packId:'science', type:'mc', emoji:'🌱', text:'What do plants need to grow big?',
      options:['Sunlight and water','Pizza','Toys','Darkness'], correct:0, time:20, level:1 },
    { packId:'science', type:'tf', emoji:'🧲', text:'A magnet can stick to metal.',
      options:['True','False'], correct:0, time:15, level:1 },
    { packId:'science', type:'mc', emoji:'🌈', text:'A rainbow is made when sunlight shines through...?',
      options:['Rain drops','Rocks','Fire','Snow'], correct:0, time:20, level:2 },
    { packId:'science', type:'mc', emoji:'🚀', text:'What do we call a person who flies to space?',
      options:['Astronaut','Doctor','Farmer','Chef'], correct:0, time:20, level:2 },
    { packId:'science', type:'tf', emoji:'🦕', text:'Dinosaurs are still alive today.',
      options:['True','False'], correct:1, time:15, level:1 },
    { packId:'science', type:'mc', emoji:'💧', text:'Which one is a liquid?',
      options:['Juice','A rock','A spoon','A book'], correct:0, time:18, level:1 },
    { packId:'science', type:'mc', emoji:'🌡️', text:'When water gets very hot it turns into...?',
      options:['Steam','Ice','Wood','Glass'], correct:0, time:20, level:2 },
    { packId:'science', type:'mc', emoji:'🐝', text:'Bees help flowers by carrying...?',
      options:['Pollen','Water','Rocks','Honey jars'], correct:0, time:20, level:3 },
    { packId:'science', type:'tf', emoji:'🌙', text:'The Moon makes its own light like the Sun.',
      options:['True','False'], correct:1, time:18, level:3 },

    /* ---------------- WORD POWER (English) ---------------- */
    { packId:'english', type:'mc', emoji:'🅱️', text:'Which word starts with the letter B?',
      options:['Ball','Cat','Dog','Egg'], correct:0, time:18, level:1 },
    { packId:'english', type:'mc', emoji:'🐱', text:'Which word rhymes with CAT?',
      options:['Hat','Dog','Sun','Cup'], correct:0, time:18, level:1 },
    { packId:'english', type:'mc', emoji:'🔤', text:'How many letters are in the word "FROG"?',
      options:['4','3','5','2'], correct:0, time:18, level:1 },
    { packId:'english', type:'mc', emoji:'🍎', text:'A, B, C, D, ... what letter comes next?',
      options:['E','F','G','Z'], correct:0, time:18, level:1 },
    { packId:'english', type:'mc', emoji:'🐶', text:'Which one is an animal?',
      options:['Tiger','Table','Truck','Tree'], correct:0, time:18, level:2 },
    { packId:'english', type:'mc', emoji:'🎨', text:'Which word means "happy"?',
      options:['Glad','Sad','Tired','Angry'], correct:0, time:20, level:2 },
    { packId:'english', type:'mc', emoji:'☀️', text:'What is the opposite of "big"?',
      options:['Small','Tall','Fast','Loud'], correct:0, time:18, level:2 },
    { packId:'english', type:'mc', emoji:'🐍', text:'Which word starts with the same sound as "snake"?',
      options:['Sun','Moon','Apple','Box'], correct:0, time:20, level:3 },
    { packId:'english', type:'tf', emoji:'📚', text:'The word "BLUE" is a colour.',
      options:['True','False'], correct:0, time:15, level:1 },

    /* ---------------- CARTOON HEROES (Bluey / Numberblocks) ---------------- */
    { packId:'cartoons', type:'mc', emoji:'🐕', text:'Bluey is what kind of animal?',
      options:['A dog','A cat','A bird','A fish'], correct:0, time:18, level:1 },
    { packId:'cartoons', type:'mc', emoji:'🐶', text:'What is the name of Bluey\'s little sister?',
      options:['Bingo','Muffin','Chloe','Honey'], correct:0, time:18, level:1 },
    { packId:'cartoons', type:'mc', emoji:'5️⃣', text:'In Numberblocks, which block is made of 5 cubes?',
      options:['Five','Three','One','Ten'], correct:0, time:18, level:1 },
    { packId:'cartoons', type:'mc', emoji:'🔟', text:'Which two Numberblocks add up to make 10?',
      options:['6 and 4','3 and 3','8 and 1','2 and 5'], correct:0, time:22, level:2 },
    { packId:'cartoons', type:'tf', emoji:'🟦', text:'Numberblock One is the smallest Numberblock.',
      options:['True','False'], correct:0, time:15, level:1 },
    { packId:'cartoons', type:'mc', emoji:'🎾', text:'What game do Bluey and Bingo love to play?',
      options:['Make-believe games','Chess','Golf','Bowling'], correct:0, time:20, level:2 },

    /* ---------------- BEAST CHALLENGE (MrBeast / trick-shot vibes) ---------------- */
    { packId:'challenge', type:'mc', emoji:'🎯', text:'A trick shot is when you...?',
      options:['Make an amazing, hard shot','Miss on purpose','Take a nap','Eat lunch'], correct:0, time:20, level:1 },
    { packId:'challenge', type:'mc', emoji:'💯', text:'You win 1 dollar, then 9 more dollars. How many dollars now?',
      options:['10','9','1','19'], correct:0, time:20, level:2 },
    { packId:'challenge', type:'mc', emoji:'🏀', text:'You score 2 baskets worth 5 points each. How many points?',
      options:['10','7','5','12'], correct:0, time:22, level:2 },
    { packId:'challenge', type:'tf', emoji:'⏱️', text:'In a challenge, going faster can earn you more points.',
      options:['True','False'], correct:0, time:15, level:1 },
    { packId:'challenge', type:'mc', emoji:'🎁', text:'There are 100 prizes. You give away 40. How many are left?',
      options:['60','40','100','140'], correct:0, time:25, level:3 },
    { packId:'challenge', type:'mc', emoji:'🔥', text:'A streak means you got many answers...?',
      options:['Right in a row','Wrong','Slowly','Backwards'], correct:0, time:18, level:1 },

    /* ---------------- COOL FACTS (world) ---------------- */
    { packId:'world', type:'mc', emoji:'🐘', text:'Which animal is the biggest?',
      options:['Elephant','Mouse','Ant','Cat'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'🦒', text:'Which animal has a very long neck?',
      options:['Giraffe','Pig','Duck','Frog'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'🌊', text:'What is the ocean full of?',
      options:['Salt water','Juice','Sand only','Milk'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'🍯', text:'Which animal makes honey?',
      options:['Bees','Cows','Dogs','Sharks'], correct:0, time:18, level:1 },
    { packId:'world', type:'tf', emoji:'🐧', text:'Penguins can fly in the sky.',
      options:['True','False'], correct:1, time:15, level:2 },
    { packId:'world', type:'mc', emoji:'🚦', text:'On a traffic light, what colour means "GO"?',
      options:['Green','Red','Yellow','Blue'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'❄️', text:'In which season does it snow?',
      options:['Winter','Summer','Spring','None'], correct:0, time:20, level:2 },

    /* ---------------- FIRST CHINESE 中文 (big character, English answers) ---------------- */
    { packId:'chinese', type:'mc', emoji:'一', text:'What number is this Chinese word?',
      options:['1','2','3','5'], correct:0, time:18, level:1 },
    { packId:'chinese', type:'mc', emoji:'二', text:'What number is this Chinese word?',
      options:['2','1','4','8'], correct:0, time:18, level:1 },
    { packId:'chinese', type:'mc', emoji:'三', text:'What number is this Chinese word?',
      options:['3','2','6','9'], correct:0, time:18, level:1 },
    { packId:'chinese', type:'mc', emoji:'大', text:'What does this Chinese word mean?',
      options:['Big','Small','Fast','Cold'], correct:0, time:20, level:2 },
    { packId:'chinese', type:'mc', emoji:'小', text:'What does this Chinese word mean?',
      options:['Small','Big','Hot','Happy'], correct:0, time:20, level:2 },
    { packId:'chinese', type:'mc', emoji:'水', text:'What does this Chinese word mean?',
      options:['Water','Fire','Tree','Rock'], correct:0, time:20, level:2 },
    { packId:'chinese', type:'mc', emoji:'火', text:'What does this Chinese word mean?',
      options:['Fire','Water','Snow','Cat'], correct:0, time:20, level:2 },
    { packId:'chinese', type:'mc', emoji:'山', text:'What does this Chinese word mean?',
      options:['Mountain','River','Sky','Dog'], correct:0, time:20, level:3 },
    { packId:'chinese', type:'mc', emoji:'人', text:'What does this Chinese word mean?',
      options:['Person','Animal','House','Ball'], correct:0, time:20, level:3 },
    { packId:'chinese', type:'mc', emoji:'日', text:'What does this Chinese word mean?',
      options:['Sun','Moon','Star','Cloud'], correct:0, time:20, level:3 }
  ]
};
