/* Default question library for Miles (age ~5.5, reads English, loves science /
   trick-shots / MrBeast / Bluey / Numberblocks). Parents can edit everything
   from the in-app editor; "Reset to defaults" re-loads this file. */
window.SEED = {
  packs: [
    { id: 'math-machine', name: 'Math Machine', emoji: '🤖', color: 'a1', generated: true },
    { id: 'science',   name: 'Science Lab',     emoji: '🔬', color: 'a3' },
    { id: 'english',   name: 'Word Power',      emoji: '📖', color: 'a4' },
    { id: 'cartoons',  name: 'Cartoon Heroes',  emoji: '📺', color: 'a2' },
    { id: 'challenge', name: 'Beast Challenge',  emoji: '🏆', color: 'a0' },
    { id: 'world',     name: 'Cool Facts',      emoji: '🌍', color: 'a5' },
    { id: 'chinese',   name: 'First Chinese 中文', emoji: '🀄', color: 'a6' }
  ],
  questions: [
    /* ---------------- SCIENCE LAB (Mark Rober vibes) ---------------- */
    { packId:'science', type:'mc', emoji:'🪐', text:'What planet do we live on?',
      options:['Earth','Mars','The Moon','The Sun'], correct:0, time:20, level:1 },
    { packId:'science', type:'mc', emoji:'🧊', text:'Ice is frozen...?',
      options:['Water','Milk','Air','Sand'], correct:0, time:20, level:1 },
    { packId:'science', type:'mc', emoji:'🌱', text:'What do plants need to grow big?',
      options:['Sunlight and water','Pizza','Toys','Darkness'], correct:0, time:20, level:1 },
    { packId:'science', type:'tf', emoji:'🧲', text:'A magnet can stick to metal.',
      options:['True','False'], correct:0, time:15, level:1 },
    { packId:'science', type:'mc', emoji:'🌈', text:'A rainbow is made when sunlight shines through...?',
      options:['Rain drops','Rocks','Fire','Snow'], correct:0, time:20, level:2 },
    { packId:'science', type:'mc', emoji:'🚀', text:'What do we call a person who flies to space?',
      options:['Astronaut','Doctor','Farmer','Chef'], correct:0, time:20, level:2 },
    { packId:'science', type:'tf', emoji:'🦕', text:'Dinosaurs are still alive today.',
      options:['True','False'], correct:1, time:15, level:1 },
    { packId:'science', type:'mc', emoji:'💧', text:'Which one is a liquid?',
      options:['Juice','A rock','A spoon','A book'], correct:0, time:18, level:1 },
    { packId:'science', type:'mc', emoji:'🌡️', text:'When water gets very hot it turns into...?',
      options:['Steam','Ice','Wood','Glass'], correct:0, time:20, level:2 },
    { packId:'science', type:'mc', emoji:'🐝', text:'Bees help flowers by carrying...?',
      options:['Pollen','Water','Rocks','Honey jars'], correct:0, time:20, level:3 },
    { packId:'science', type:'tf', emoji:'🌙', text:'The Moon makes its own light like the Sun.',
      options:['True','False'], correct:1, time:18, level:3 },
    { packId:'science', type:'mc', emoji:'🦋', text:'A caterpillar grows up to become a...?',
      options:['Butterfly','Spider','Fish','Bird'], correct:0, time:18, level:1 },
    { packId:'science', type:'mc', emoji:'🐸', text:'What do we call a baby frog?',
      options:['Tadpole','Puppy','Chick','Kitten'], correct:0, time:20, level:2 },
    { packId:'science', type:'mc', emoji:'🌳', text:'Trees help us by making the air...?',
      options:['Fresh to breathe','Dirty','Hot','Loud'], correct:0, time:20, level:2 },
    { packId:'science', type:'mc', emoji:'🌬️', text:'What do we call moving air?',
      options:['Wind','Rain','Snow','Sand'], correct:0, time:18, level:1 },
    { packId:'science', type:'mc', emoji:'❤️', text:'Which part of your body pumps blood?',
      options:['Heart','Hair','Teeth','Toes'], correct:0, time:20, level:2 },
    { packId:'science', type:'mc', emoji:'🦴', text:'What helps your body stand up tall and strong?',
      options:['Bones','Bubbles','Clouds','Paper'], correct:0, time:20, level:2 },
    { packId:'science', type:'tf', emoji:'☀️', text:'The Sun is very, very hot.',
      options:['True','False'], correct:0, time:15, level:1 },
    { packId:'science', type:'mc', emoji:'🌧️', text:'Water that falls from the clouds is called...?',
      options:['Rain','Glass','Wood','Sand'], correct:0, time:18, level:1 },
    { packId:'science', type:'mc', emoji:'☁️', text:'Clouds up in the sky are made of...?',
      options:['Tiny water drops','Cotton','Smoke','Marshmallows'], correct:0, time:22, level:3 },
    { packId:'science', type:'mc', emoji:'🎨', text:'If you mix red and yellow paint, what colour do you get?',
      options:['Orange','Green','Black','Blue'], correct:0, time:20, level:2 },
    { packId:'science', type:'mc', emoji:'🐜', text:'How many legs does an insect like an ant have?',
      options:['6','4','8','2'], correct:0, time:22, level:3 },
    { packId:'science', type:'mc', emoji:'🪶', text:'Which one floats down more slowly, a feather or a rock?',
      options:['A feather','A rock','Both the same','Neither'], correct:0, time:20, level:2 },
    { packId:'science', type:'mc', emoji:'🌋', text:'What hot, runny stuff comes out of a volcano?',
      options:['Lava','Ice','Juice','Sand'], correct:0, time:20, level:2 },
    { packId:'science', type:'mc', emoji:'🐦', text:"What covers a bird's body?",
      options:['Feathers','Scales','Fur only','Leaves'], correct:0, time:18, level:1 },
    { packId:'science', type:'tf', emoji:'🌍', text:'The Earth is shaped like a giant ball.',
      options:['True','False'], correct:0, time:15, level:1 },
    { packId:'science', type:'mc', emoji:'🐟', text:'How do fish breathe under the water?',
      options:['With their gills','With a nose','With their ears','They hold their breath'], correct:0, time:20, level:2 },
    { packId:'science', type:'mc', emoji:'🦷', text:'What should you do to keep your teeth strong and healthy?',
      options:['Brush them every day','Eat only candy','Never drink water','Chew on rocks'], correct:0, time:18, level:1 },
    { packId:'science', type:'mc', emoji:'🧠', text:'Which body part helps you think and remember things?',
      options:['Brain','Elbow','Knee','Heel'], correct:0, time:20, level:2 },
    { packId:'science', type:'mc', emoji:'👃', text:'Which part of your body do you use to smell?',
      options:['Nose','Ear','Knee','Foot'], correct:0, time:18, level:1 },
    { packId:'science', type:'mc', emoji:'👂', text:'Which part of your body do you use to hear sounds?',
      options:['Ears','Eyes','Nose','Toes'], correct:0, time:18, level:1 },
    { packId:'science', type:'tf', emoji:'🌞', text:'Plants use sunlight to make their own food.',
      options:['True','False'], correct:0, time:18, level:3 },
    { packId:'science', type:'mc', emoji:'⚡', text:'What makes our lights and TV turn on?',
      options:['Electricity','Mud','Leaves','Snow'], correct:0, time:20, level:2 },
    { packId:'science', type:'mc', emoji:'🌊', text:'What do we call the water that rolls up and down at the beach?',
      options:['Waves','Hills','Rocks','Clouds'], correct:0, time:20, level:2 },
    { packId:'science', type:'mc', emoji:'🪨', text:'Which one of these is a solid?',
      options:['A rock','Juice','Steam','Wind'], correct:0, time:20, level:2 },
    { packId:'science', type:'tf', emoji:'💨', text:'We need to breathe air to stay alive.',
      options:['True','False'], correct:0, time:15, level:1 },
    { packId:'science', type:'tf', emoji:'❄️', text:'Ice is colder than warm water.',
      options:['True','False'], correct:0, time:15, level:1 },
    { packId:'science', type:'mc', emoji:'🐣', text:'Which baby animal hatches out of an egg?',
      options:['A chick','A puppy','A kitten','A foal'], correct:0, time:18, level:2 },

    /* ---------------- WORD POWER (English) ---------------- */
    { packId:'english', type:'mc', emoji:'🅱️', text:'Which word starts with the letter B?',
      options:['Ball','Cat','Dog','Egg'], correct:0, time:18, level:1 },
    { packId:'english', type:'mc', emoji:'🐱', text:'Which word rhymes with CAT?',
      options:['Hat','Dog','Sun','Cup'], correct:0, time:18, level:1 },
    { packId:'english', type:'mc', emoji:'🔤', text:'How many letters are in the word "FROG"?',
      options:['4','3','5','2'], correct:0, time:18, level:1 },
    { packId:'english', type:'mc', emoji:'🍎', text:'A, B, C, D, ... what letter comes next?',
      options:['E','F','G','Z'], correct:0, time:18, level:1 },
    { packId:'english', type:'mc', emoji:'🐶', text:'Which one is an animal?',
      options:['Tiger','Table','Truck','Tree'], correct:0, time:18, level:2 },
    { packId:'english', type:'mc', emoji:'🎨', text:'Which word means "happy"?',
      options:['Glad','Sad','Tired','Angry'], correct:0, time:20, level:2 },
    { packId:'english', type:'mc', emoji:'☀️', text:'What is the opposite of "big"?',
      options:['Small','Tall','Fast','Loud'], correct:0, time:18, level:2 },
    { packId:'english', type:'mc', emoji:'🐍', text:'Which word starts with the same sound as "snake"?',
      options:['Sun','Moon','Apple','Box'], correct:0, time:20, level:3 },
    { packId:'english', type:'tf', emoji:'📚', text:'The word "BLUE" is a colour.',
      options:['True','False'], correct:0, time:15, level:1 },
    { packId:'english', type:'mc', emoji:'🧊', text:'What is the opposite of "hot"?',
      options:['Cold','Big','Fast','Loud'], correct:0, time:18, level:2 },
    { packId:'english', type:'mc', emoji:'🥤', text:'Which word starts with the letter C?',
      options:['Cup','Apple','Dog','Egg'], correct:0, time:18, level:1 },
    { packId:'english', type:'mc', emoji:'🌳', text:'Which word rhymes with "BEE"?',
      options:['Tree','Dog','Hat','Cup'], correct:0, time:18, level:2 },
    { packId:'english', type:'mc', emoji:'⬇️', text:'What is the opposite of "up"?',
      options:['Down','Left','Big','Fast'], correct:0, time:18, level:1 },
    { packId:'english', type:'mc', emoji:'🔢', text:'How many letters are in the word "SUN"?',
      options:['3','2','4','5'], correct:0, time:18, level:1 },
    { packId:'english', type:'tf', emoji:'🐾', text:'The words "DOG" and "CAT" both name animals.',
      options:['True','False'], correct:0, time:15, level:1 },

    /* ---------------- CARTOON HEROES (Bluey / Numberblocks) ---------------- */
    { packId:'cartoons', type:'mc', emoji:'🐕', text:'Bluey is what kind of animal?',
      options:['A dog','A cat','A bird','A fish'], correct:0, time:18, level:1 },
    { packId:'cartoons', type:'mc', emoji:'🐶', text:'What is the name of Bluey\'s little sister?',
      options:['Bingo','Muffin','Chloe','Honey'], correct:0, time:18, level:1 },
    { packId:'cartoons', type:'mc', emoji:'5️⃣', text:'In Numberblocks, which block is made of 5 cubes?',
      options:['Five','Three','One','Ten'], correct:0, time:18, level:1 },
    { packId:'cartoons', type:'mc', emoji:'🔟', text:'Which two Numberblocks add up to make 10?',
      options:['6 and 4','3 and 3','8 and 1','2 and 5'], correct:0, time:22, level:2 },
    { packId:'cartoons', type:'tf', emoji:'🟦', text:'Numberblock One is the smallest Numberblock.',
      options:['True','False'], correct:0, time:15, level:1 },
    { packId:'cartoons', type:'mc', emoji:'🎾', text:'What game do Bluey and Bingo love to play?',
      options:['Make-believe games','Chess','Golf','Bowling'], correct:0, time:20, level:2 },
    { packId:'cartoons', type:'mc', emoji:'🐶', text:"What is the name of Bluey and Bingo's dad?",
      options:['Bandit','Bingo','Muffin','Lucky'], correct:0, time:18, level:2 },
    { packId:'cartoons', type:'mc', emoji:'🐕', text:"What is the name of Bluey and Bingo's mum?",
      options:['Chilli','Honey','Bingo','Muffin'], correct:0, time:18, level:2 },
    { packId:'cartoons', type:'mc', emoji:'7️⃣', text:'In Numberblocks, which block is made of 7 cubes?',
      options:['Seven','Two','Four','Ten'], correct:0, time:18, level:1 },
    { packId:'cartoons', type:'mc', emoji:'➕', text:'In Numberblocks, what do you get when Two and Two join up?',
      options:['Four','Three','Five','One'], correct:0, time:20, level:2 },
    { packId:'cartoons', type:'mc', emoji:'🔟', text:'Numberblock Ten is made of how many cubes?',
      options:['10','5','2','7'], correct:0, time:18, level:1 },
    { packId:'cartoons', type:'tf', emoji:'🐾', text:'Bluey is a TV show about a family of dogs.',
      options:['True','False'], correct:0, time:15, level:1 },

    /* ---------------- BEAST CHALLENGE (MrBeast / trick-shot vibes) ---------------- */
    { packId:'challenge', type:'mc', emoji:'🎯', text:'A trick shot is when you...?',
      options:['Make an amazing, hard shot','Miss on purpose','Take a nap','Eat lunch'], correct:0, time:20, level:1 },
    { packId:'challenge', type:'mc', emoji:'💯', text:'You win 1 dollar, then 9 more dollars. How many dollars now?',
      options:['10','9','1','19'], correct:0, time:20, level:2 },
    { packId:'challenge', type:'mc', emoji:'🏀', text:'You score 2 baskets worth 5 points each. How many points?',
      options:['10','7','5','12'], correct:0, time:22, level:2 },
    { packId:'challenge', type:'tf', emoji:'⏱️', text:'In a challenge, going faster can earn you more points.',
      options:['True','False'], correct:0, time:15, level:1 },
    { packId:'challenge', type:'mc', emoji:'🎁', text:'There are 100 prizes. You give away 40. How many are left?',
      options:['60','40','100','140'], correct:0, time:25, level:3 },
    { packId:'challenge', type:'mc', emoji:'🔥', text:'A streak means you got many answers...?',
      options:['Right in a row','Wrong','Slowly','Backwards'], correct:0, time:18, level:1 },
    { packId:'challenge', type:'mc', emoji:'🪙', text:'You have 5 coins and find 5 more. How many coins now?',
      options:['10','9','5','15'], correct:0, time:20, level:1 },
    { packId:'challenge', type:'mc', emoji:'🍪', text:'There are 20 cookies. You eat 10. How many are left?',
      options:['10','20','0','30'], correct:0, time:20, level:2 },
    { packId:'challenge', type:'mc', emoji:'⚽', text:'You score 3 goals worth 10 points each. How many points?',
      options:['30','13','3','40'], correct:0, time:22, level:2 },
    { packId:'challenge', type:'mc', emoji:'🎈', text:'There are 50 balloons. 30 pop. How many balloons are left?',
      options:['20','30','50','80'], correct:0, time:25, level:3 },
    { packId:'challenge', type:'tf', emoji:'🤝', text:'In a team challenge, helping your teammate is a good idea.',
      options:['True','False'], correct:0, time:15, level:1 },
    { packId:'challenge', type:'mc', emoji:'⏳', text:'If you have 60 seconds and use 20, how many seconds are left?',
      options:['40','20','60','80'], correct:0, time:22, level:2 },

    /* ---------------- COOL FACTS (world) ---------------- */
    { packId:'world', type:'mc', emoji:'🐘', text:'Which animal is the biggest?',
      options:['Elephant','Mouse','Ant','Cat'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'🦒', text:'Which animal has a very long neck?',
      options:['Giraffe','Pig','Duck','Frog'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'🌊', text:'What is the ocean full of?',
      options:['Salt water','Juice','Sand only','Milk'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'🍯', text:'Which animal makes honey?',
      options:['Bees','Cows','Dogs','Sharks'], correct:0, time:18, level:1 },
    { packId:'world', type:'tf', emoji:'🐧', text:'Penguins can fly in the sky.',
      options:['True','False'], correct:1, time:15, level:2 },
    { packId:'world', type:'mc', emoji:'🚦', text:'On a traffic light, what colour means "GO"?',
      options:['Green','Red','Yellow','Blue'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'❄️', text:'In which season does it snow?',
      options:['Winter','Summer','Spring','None'], correct:0, time:20, level:2 },
    { packId:'world', type:'mc', emoji:'🐆', text:'Which animal is the fastest runner on land?',
      options:['Cheetah','Turtle','Snail','Pig'], correct:0, time:20, level:2 },
    { packId:'world', type:'mc', emoji:'🐢', text:'Which animal carries its home on its back?',
      options:['Turtle','Dog','Horse','Fish'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'🦘', text:'Which animal hops and carries its baby in a pouch?',
      options:['Kangaroo','Cow','Duck','Cat'], correct:0, time:20, level:2 },
    { packId:'world', type:'mc', emoji:'🐙', text:'How many arms does an octopus have?',
      options:['8','2','4','6'], correct:0, time:20, level:2 },
    { packId:'world', type:'mc', emoji:'🦁', text:'Which animal is called the "King of the Jungle"?',
      options:['Lion','Rabbit','Mouse','Frog'], correct:0, time:18, level:1 },
    { packId:'world', type:'tf', emoji:'🐳', text:'The blue whale is the biggest animal in the world.',
      options:['True','False'], correct:0, time:18, level:2 },
    { packId:'world', type:'mc', emoji:'🍌', text:'What do monkeys love to eat?',
      options:['Bananas','Rocks','Shoes','Paper'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'🐪', text:'Which animal can travel a long way across the hot desert?',
      options:['Camel','Penguin','Polar bear','Seal'], correct:0, time:20, level:2 },
    { packId:'world', type:'mc', emoji:'🦉', text:'Which bird is awake at night and says "hoo"?',
      options:['Owl','Chicken','Duck','Parrot'], correct:0, time:20, level:2 },
    { packId:'world', type:'mc', emoji:'⭐', text:'What twinkles in the sky at night?',
      options:['Stars','Cars','Shoes','Rocks'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'🌵', text:'A spiky cactus grows in a hot, dry place called the...?',
      options:['Desert','Ocean','Snow','City'], correct:0, time:20, level:2 },
    { packId:'world', type:'mc', emoji:'🍂', text:'In which season do leaves turn brown and fall down?',
      options:['Autumn','Summer','Winter','Spring'], correct:0, time:20, level:3 },
    { packId:'world', type:'mc', emoji:'🐊', text:'Which animal has big sharp teeth and lives in rivers?',
      options:['Crocodile','Sheep','Bunny','Goat'], correct:0, time:20, level:2 },
    { packId:'world', type:'mc', emoji:'🌻', text:'A sunflower likes to turn and face the...?',
      options:['Sun','Moon','Ground','Wall'], correct:0, time:20, level:2 },
    { packId:'world', type:'tf', emoji:'🐜', text:'An ant can lift things much bigger than itself.',
      options:['True','False'], correct:0, time:18, level:3 },
    { packId:'world', type:'mc', emoji:'🐘', text:'Which animal has a long trunk on its face?',
      options:['Elephant','Rabbit','Fish','Bird'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'🦓', text:'Which animal looks like a horse with black-and-white stripes?',
      options:['Zebra','Cow','Pig','Sheep'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'🐼', text:'Which black-and-white animal loves to munch bamboo?',
      options:['Panda','Lion','Shark','Owl'], correct:0, time:20, level:2 },
    { packId:'world', type:'mc', emoji:'🦈', text:'Which big sea animal has rows of sharp teeth?',
      options:['Shark','Cow','Sheep','Chicken'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'🐮', text:'Which farm animal gives us milk?',
      options:['Cow','Chicken','Sheep','Horse'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'🐓', text:'Which animal says "cock-a-doodle-doo" in the morning?',
      options:['Rooster','Cow','Cat','Frog'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'🐑', text:'What do we get from a sheep to make warm sweaters?',
      options:['Wool','Milk','Eggs','Honey'], correct:0, time:20, level:2 },
    { packId:'world', type:'mc', emoji:'🐍', text:'Which animal is long, has no legs, and slithers on the ground?',
      options:['Snake','Dog','Bird','Cat'], correct:0, time:18, level:1 },
    { packId:'world', type:'mc', emoji:'🐻', text:'Which big furry animal sleeps all winter long?',
      options:['Bear','Bee','Fish','Duck'], correct:0, time:20, level:2 },
    { packId:'world', type:'mc', emoji:'🦜', text:'Which colourful bird can copy words and "talk"?',
      options:['Parrot','Owl','Penguin','Crow'], correct:0, time:20, level:2 },
    { packId:'world', type:'mc', emoji:'🕷️', text:'How many legs does a spider have?',
      options:['8','6','4','2'], correct:0, time:20, level:3 },
    { packId:'world', type:'tf', emoji:'🌎', text:'Most of the Earth is covered by water.',
      options:['True','False'], correct:0, time:18, level:3 },

    /* ---------------- FIRST CHINESE 中文 (big character, English answers) ---------------- */
    { packId:'chinese', type:'mc', emoji:'一', text:'What number is this Chinese word?',
      options:['1','2','3','5'], correct:0, time:18, level:1 },
    { packId:'chinese', type:'mc', emoji:'二', text:'What number is this Chinese word?',
      options:['2','1','4','8'], correct:0, time:18, level:1 },
    { packId:'chinese', type:'mc', emoji:'三', text:'What number is this Chinese word?',
      options:['3','2','6','9'], correct:0, time:18, level:1 },
    { packId:'chinese', type:'mc', emoji:'大', text:'What does this Chinese word mean?',
      options:['Big','Small','Fast','Cold'], correct:0, time:20, level:2 },
    { packId:'chinese', type:'mc', emoji:'小', text:'What does this Chinese word mean?',
      options:['Small','Big','Hot','Happy'], correct:0, time:20, level:2 },
    { packId:'chinese', type:'mc', emoji:'水', text:'What does this Chinese word mean?',
      options:['Water','Fire','Tree','Rock'], correct:0, time:20, level:2 },
    { packId:'chinese', type:'mc', emoji:'火', text:'What does this Chinese word mean?',
      options:['Fire','Water','Snow','Cat'], correct:0, time:20, level:2 },
    { packId:'chinese', type:'mc', emoji:'山', text:'What does this Chinese word mean?',
      options:['Mountain','River','Sky','Dog'], correct:0, time:20, level:3 },
    { packId:'chinese', type:'mc', emoji:'人', text:'What does this Chinese word mean?',
      options:['Person','Animal','House','Ball'], correct:0, time:20, level:3 },
    { packId:'chinese', type:'mc', emoji:'日', text:'What does this Chinese word mean?',
      options:['Sun','Moon','Star','Cloud'], correct:0, time:20, level:3 },
    { packId:'chinese', type:'mc', emoji:'四', text:'What number is this Chinese word?',
      options:['4','3','5','7'], correct:0, time:18, level:1 },
    { packId:'chinese', type:'mc', emoji:'五', text:'What number is this Chinese word?',
      options:['5','2','6','9'], correct:0, time:18, level:1 },
    { packId:'chinese', type:'mc', emoji:'月', text:'What does this Chinese word mean?',
      options:['Moon','Sun','Star','Tree'], correct:0, time:20, level:2 },
    { packId:'chinese', type:'mc', emoji:'木', text:'What does this Chinese word mean?',
      options:['Tree','Rock','Water','Fire'], correct:0, time:20, level:2 },
    { packId:'chinese', type:'mc', emoji:'口', text:'What does this Chinese word mean?',
      options:['Mouth','Eye','Hand','Ear'], correct:0, time:20, level:3 }
  ]
};
