/* ---------- Shared Chinese data for every 中文 game ----------
   One bank, many games: the same characters come back in Character Quest,
   Whack-a-Char, Bingo, the Garden and so on, so each meeting deepens the
   memory. Games reach it through window.ZH.

   WORDS       single characters  { ch, en, pic, lv }
   WORDS2      two-character words
   SENTS       silly sentences (seg = word tiles for Sentence Builder)
   BUILD       compound characters made of pieces (Character Builder)
   TWINS       look-alike pairs (Spot the Twin)
   OPPOSITES   antonym pairs
   COUNT       nouns with their measure words (Count & Say)
   Pictures stick to older emoji so they render on more devices. */
window.ZH = (function () {
  const WORDS = [
    { ch: '一', en: 'one',   pic: '1️⃣', lv: 1 },
    { ch: '二', en: 'two',   pic: '2️⃣', lv: 1 },
    { ch: '三', en: 'three', pic: '3️⃣', lv: 1 },
    { ch: '日', en: 'sun',   pic: '☀️', lv: 1 },
    { ch: '月', en: 'moon',  pic: '🌙', lv: 1 },
    { ch: '水', en: 'water', pic: '💧', lv: 1 },
    { ch: '火', en: 'fire',  pic: '🔥', lv: 1 },
    { ch: '山', en: 'mountain', pic: '⛰️', lv: 1 },
    { ch: '木', en: 'tree',  pic: '🌳', lv: 1 },
    { ch: '口', en: 'mouth', pic: '👄', lv: 1 },
    { ch: '手', en: 'hand',  pic: '✋', lv: 1 },
    { ch: '人', en: 'person', pic: '🚶', lv: 1 },
    { ch: '大', en: 'big',   pic: '',   lv: 1 },
    { ch: '小', en: 'small', pic: '',   lv: 1 },
    /* level 2 — more words */
    { ch: '四', en: 'four',  pic: '4️⃣', lv: 2 },
    { ch: '五', en: 'five',  pic: '5️⃣', lv: 2 },
    { ch: '狗', en: 'dog',   pic: '🐶', lv: 2 },
    { ch: '貓', en: 'cat',   pic: '🐱', lv: 2 },
    { ch: '魚', en: 'fish',  pic: '🐟', lv: 2 },
    { ch: '鳥', en: 'bird',  pic: '🐦', lv: 2 },
    { ch: '牛', en: 'cow',   pic: '🐮', lv: 2 },
    { ch: '馬', en: 'horse', pic: '🐴', lv: 2 },
    { ch: '羊', en: 'sheep', pic: '🐑', lv: 2 },
    { ch: '豬', en: 'pig',   pic: '🐷', lv: 2 },
    { ch: '雞', en: 'chicken', pic: '🐔', lv: 2 },
    { ch: '鴨', en: 'duck',  pic: '🦆', lv: 2 },
    { ch: '熊', en: 'bear',  pic: '🐻', lv: 2 },
    { ch: '虎', en: 'tiger', pic: '🐯', lv: 2 },
    { ch: '花', en: 'flower', pic: '🌸', lv: 2 },
    { ch: '雨', en: 'rain',  pic: '🌧️', lv: 2 },
    { ch: '星', en: 'star',  pic: '⭐', lv: 2 },
    { ch: '車', en: 'car',   pic: '🚗', lv: 2 },
    { ch: '家', en: 'home',  pic: '🏠', lv: 2 },
    { ch: '球', en: 'ball',  pic: '⚽', lv: 2 },
    { ch: '果', en: 'fruit', pic: '🍎', lv: 2 },
    { ch: '好', en: 'good',  pic: '👍', lv: 2 },
    { ch: '上', en: 'up',    pic: '',   lv: 2 },
    { ch: '下', en: 'down',  pic: '',   lv: 2 },
    { ch: '天', en: 'sky',   pic: '',   lv: 2 },
    /* level 3 — word master */
    { ch: '六', en: 'six',   pic: '6️⃣', lv: 3 },
    { ch: '七', en: 'seven', pic: '7️⃣', lv: 3 },
    { ch: '八', en: 'eight', pic: '8️⃣', lv: 3 },
    { ch: '九', en: 'nine',  pic: '9️⃣', lv: 3 },
    { ch: '十', en: 'ten',   pic: '🔟', lv: 3 },
    { ch: '兔', en: 'rabbit', pic: '🐰', lv: 3 },
    { ch: '蟲', en: 'bug',   pic: '🐛', lv: 3 },
    { ch: '草', en: 'grass', pic: '🌱', lv: 3 },
    { ch: '雪', en: 'snow',  pic: '❄️', lv: 3 },
    { ch: '雲', en: 'cloud', pic: '☁️', lv: 3 },
    { ch: '門', en: 'door',  pic: '🚪', lv: 3 },
    { ch: '書', en: 'book',  pic: '📖', lv: 3 },
    { ch: '筆', en: 'pen',   pic: '✏️', lv: 3 },
    { ch: '蛋', en: 'egg',   pic: '🥚', lv: 3 },
    { ch: '米', en: 'rice',  pic: '🍚', lv: 3 },
    { ch: '瓜', en: 'melon', pic: '🍉', lv: 3 },
    { ch: '目', en: 'eye',   pic: '👀', lv: 3 },
    { ch: '耳', en: 'ear',   pic: '👂', lv: 3 },
    { ch: '心', en: 'heart', pic: '❤️', lv: 3 },
    { ch: '王', en: 'king',  pic: '👑', lv: 3 },
    { ch: '象', en: 'elephant', pic: '🐘', lv: 3 },
    { ch: '猴', en: 'monkey', pic: '🐵', lv: 3 },
    { ch: '龍', en: 'dragon', pic: '🐉', lv: 3 },
    { ch: '蛇', en: 'snake', pic: '🐍', lv: 3 },
    { ch: '龜', en: 'turtle', pic: '🐢', lv: 3 },
    { ch: '蝶', en: 'butterfly', pic: '🦋', lv: 3 },
    { ch: '茶', en: 'tea',   pic: '🍵', lv: 3 },
    { ch: '肉', en: 'meat',  pic: '🍖', lv: 3 },
    { ch: '電', en: 'electricity', pic: '⚡', lv: 3 },
    { ch: '風', en: 'wind',  pic: '🌬️', lv: 3 },
    { ch: '燈', en: 'lamp',  pic: '💡', lv: 3 },
    { ch: '白', en: 'white', pic: '⚪', lv: 3 },
    { ch: '黑', en: 'black', pic: '⚫', lv: 3 },
    { ch: '紅', en: 'red',   pic: '🔴', lv: 3 },
    { ch: '藍', en: 'blue',  pic: '🔵', lv: 3 },
    { ch: '鞋', en: 'shoe',  pic: '👟', lv: 3 },
    { ch: '愛', en: 'love',  pic: '💖', lv: 3 },
    /* pieces & parts — used by Character Builder and the twins game */
    { ch: '女', en: 'girl',   pic: '👧', lv: 2 },
    { ch: '子', en: 'child',  pic: '👶', lv: 2 },
    { ch: '田', en: 'field',  pic: '🌾', lv: 2 },
    { ch: '土', en: 'dirt',   pic: '🪴', lv: 2 },
    { ch: '中', en: 'middle', pic: '🎯', lv: 2 },
    { ch: '力', en: 'strength', pic: '💪', lv: 3 },
    { ch: '石', en: 'stone',  pic: '🪨', lv: 3 },
    { ch: '生', en: 'born',   pic: '🐣', lv: 3 },
    /* compound characters — grown in Character Builder */
    { ch: '明', en: 'bright', pic: '🔆', lv: 3 },
    { ch: '林', en: 'woods',  pic: '🌲', lv: 3 },
    { ch: '森', en: 'forest', pic: '🏕️', lv: 3 },
    { ch: '朋', en: 'friend', pic: '👫', lv: 3 },
    { ch: '休', en: 'rest',   pic: '😴', lv: 3 },
    { ch: '男', en: 'boy',    pic: '👦', lv: 3 },
    { ch: '思', en: 'think',  pic: '🤔', lv: 3 },
    { ch: '問', en: 'ask',    pic: '❓', lv: 3 },
    { ch: '泉', en: 'spring water', pic: '⛲', lv: 3 },
    { ch: '晶', en: 'sparkle', pic: '✨', lv: 3 },
    { ch: '媽', en: 'mom',    pic: '👩', lv: 3 },
    { ch: '炎', en: 'blazing hot', pic: '🌡️', lv: 3 },
    { ch: '出', en: 'go out', pic: '🏃', lv: 3 },
    { ch: '鳴', en: 'chirp',  pic: '🎵', lv: 3 },
    { ch: '品', en: 'taste',  pic: '👅', lv: 3 },
    { ch: '旦', en: 'dawn',   pic: '🌅', lv: 3 },
    { ch: '尖', en: 'pointy', pic: '📍', lv: 3 },
    { ch: '李', en: 'plum',   pic: '🍑', lv: 3 },
    { ch: '古', en: 'ancient', pic: '🏺', lv: 3 },
    { ch: '聞', en: 'smell',  pic: '👃', lv: 3 },
    { ch: '岩', en: 'rock',   pic: '🗿', lv: 3 },
    { ch: '仙', en: 'fairy',  pic: '🧚', lv: 3 },
    { ch: '里', en: 'village', pic: '🏘️', lv: 3 }
  ];

  /* characters that sound exactly the same (mù) — keep them out of each
     other's answer rows in the sound-based modes, where the ear can't
     tell them apart */
  const HOMOPHONES = [['木', '目'], ['子', '紫'], ['石', '十'], ['生', '聲']];

  const WORDS2 = [
    { ch: '太陽', en: 'sun',      pic: '☀️', lv: 1 },
    { ch: '月亮', en: 'moon',     pic: '🌙', lv: 1 },
    { ch: '星星', en: 'star',     pic: '⭐', lv: 1 },
    { ch: '小狗', en: 'dog',      pic: '🐶', lv: 1 },
    { ch: '小貓', en: 'cat',      pic: '🐱', lv: 1 },
    { ch: '小鳥', en: 'bird',     pic: '🐦', lv: 1 },
    { ch: '大象', en: 'elephant', pic: '🐘', lv: 1 },
    { ch: '老虎', en: 'tiger',    pic: '🐯', lv: 1 },
    { ch: '兔子', en: 'rabbit',   pic: '🐰', lv: 1 },
    { ch: '火車', en: 'train',    pic: '🚂', lv: 1 },
    { ch: '汽車', en: 'car',      pic: '🚗', lv: 1 },
    { ch: '蘋果', en: 'apple',    pic: '🍎', lv: 1 },
    { ch: '香蕉', en: 'banana',   pic: '🍌', lv: 1 },
    { ch: '雨傘', en: 'umbrella', pic: '☔', lv: 1 },
    { ch: '房子', en: 'house',    pic: '🏠', lv: 1 },
    /* level 2 — more words */
    { ch: '恐龍', en: 'dinosaur', pic: '🦖', lv: 2 },
    { ch: '熊貓', en: 'panda',    pic: '🐼', lv: 2 },
    { ch: '猴子', en: 'monkey',   pic: '🐵', lv: 2 },
    { ch: '鴨子', en: 'duck',     pic: '🦆', lv: 2 },
    { ch: '青蛙', en: 'frog',     pic: '🐸', lv: 2 },
    { ch: '烏龜', en: 'turtle',   pic: '🐢', lv: 2 },
    { ch: '蜜蜂', en: 'bee',      pic: '🐝', lv: 2 },
    { ch: '飛機', en: 'airplane', pic: '✈️', lv: 2 },
    { ch: '下雨', en: 'rain',     pic: '🌧️', lv: 2 },
    { ch: '雪人', en: 'snowman',  pic: '⛄', lv: 2 },
    { ch: '彩虹', en: 'rainbow',  pic: '🌈', lv: 2 },
    { ch: '眼睛', en: 'eyes',     pic: '👀', lv: 2 },
    { ch: '耳朵', en: 'ear',      pic: '👂', lv: 2 },
    { ch: '鼻子', en: 'nose',     pic: '👃', lv: 2 },
    { ch: '嘴巴', en: 'mouth',    pic: '👄', lv: 2 },
    { ch: '牛奶', en: 'milk',     pic: '🥛', lv: 2 },
    { ch: '雞蛋', en: 'egg',      pic: '🥚', lv: 2 },
    { ch: '西瓜', en: 'watermelon', pic: '🍉', lv: 2 },
    { ch: '草莓', en: 'strawberry', pic: '🍓', lv: 2 },
    { ch: '麵包', en: 'bread',    pic: '🍞', lv: 2 },
    /* level 3 — word master */
    { ch: '蝴蝶', en: 'butterfly', pic: '🦋', lv: 3 },
    { ch: '蜘蛛', en: 'spider',   pic: '🕷️', lv: 3 },
    { ch: '鯊魚', en: 'shark',    pic: '🦈', lv: 3 },
    { ch: '海豚', en: 'dolphin',  pic: '🐬', lv: 3 },
    { ch: '企鵝', en: 'penguin',  pic: '🐧', lv: 3 },
    { ch: '獅子', en: 'lion',     pic: '🦁', lv: 3 },
    { ch: '斑馬', en: 'zebra',    pic: '🦓', lv: 3 },
    { ch: '火山', en: 'volcano',  pic: '🌋', lv: 3 },
    { ch: '地球', en: 'Earth',    pic: '🌍', lv: 3 },
    { ch: '火箭', en: 'rocket',   pic: '🚀', lv: 3 },
    { ch: '足球', en: 'soccer ball', pic: '⚽', lv: 3 },
    { ch: '籃球', en: 'basketball', pic: '🏀', lv: 3 },
    { ch: '電話', en: 'telephone', pic: '📞', lv: 3 },
    { ch: '電燈', en: 'lamp',     pic: '💡', lv: 3 },
    { ch: '電視', en: 'TV',       pic: '📺', lv: 3 },
    { ch: '書包', en: 'backpack', pic: '🎒', lv: 3 },
    { ch: '鉛筆', en: 'pencil',   pic: '✏️', lv: 3 },
    { ch: '剪刀', en: 'scissors', pic: '✂️', lv: 3 },
    { ch: '帽子', en: 'hat',      pic: '🎩', lv: 3 },
    { ch: '鞋子', en: 'shoes',    pic: '👟', lv: 3 },
    { ch: '皇冠', en: 'crown',    pic: '👑', lv: 3 },
    { ch: '禮物', en: 'present',  pic: '🎁', lv: 3 },
    { ch: '蛋糕', en: 'cake',     pic: '🎂', lv: 3 },
    { ch: '糖果', en: 'candy',    pic: '🍬', lv: 3 }
  ];

  const SENTS = [
    { ch: '貓咪愛魚', seg: '貓咪/愛/魚',   en: 'The kitty loves fish',        pic: '🐱🐟', lv: 1 },
    { ch: '狗狗開車', seg: '狗狗/開/車',   en: 'The doggy drives a car',      pic: '🐶🚗', lv: 1 },
    { ch: '豬在跳舞', seg: '豬/在/跳舞',   en: 'The pig is dancing',          pic: '🐷💃', lv: 1 },
    { ch: '熊貓吃飯', seg: '熊貓/吃/飯',   en: 'The panda eats rice',         pic: '🐼🍚', lv: 1 },
    { ch: '魚會飛', seg: '魚/會/飛',     en: 'The fish can fly',            pic: '🐟✈️', lv: 1 },
    { ch: '兔子唱歌', seg: '兔子/唱歌',   en: 'The bunny sings a song',      pic: '🐰🎤', lv: 1 },
    { ch: '老虎刷牙', seg: '老虎/刷牙',   en: 'The tiger brushes its teeth', pic: '🐯🦷', lv: 1 },
    { ch: '雞在看書', seg: '雞/在/看書',   en: 'The chicken is reading',      pic: '🐔📖', lv: 1 },
    { ch: '馬吃蛋糕', seg: '馬/吃/蛋糕',   en: 'The horse eats cake',         pic: '🐴🎂', lv: 1 },
    { ch: '下雨了', seg: '下雨/了',     en: 'It is raining',               pic: '🌧️☂️', lv: 1 },
    { ch: '鴨子游泳', seg: '鴨子/游泳',   en: 'The duck is swimming',        pic: '🦆🌊', lv: 1 },
    { ch: '熊在睡覺', seg: '熊/在/睡覺',   en: 'The bear is sleeping',        pic: '🐻💤', lv: 1 },
    { ch: '貓咪畫畫', seg: '貓咪/畫畫',   en: 'The kitty is painting',       pic: '🐱🎨', lv: 1 },
    { ch: '鴨子坐船', seg: '鴨子/坐/船',   en: 'The duck rides a boat',       pic: '🦆⛵', lv: 1 },
    { ch: '豬豬愛花', seg: '豬豬/愛/花',   en: 'The piggy loves flowers',     pic: '🐷🌸', lv: 1 },
    { ch: '鳥在洗澡', seg: '鳥/在/洗澡',   en: 'The bird takes a bath',       pic: '🐦🛁', lv: 1 },
    { ch: '狗狗玩球', seg: '狗狗/玩/球',   en: 'The doggy plays ball',        pic: '🐶⚽', lv: 1 },
    { ch: '熊吃麵', seg: '熊/吃/麵',     en: 'The bear eats noodles',       pic: '🐻🍜', lv: 1 },
    { ch: '魚看月亮', seg: '魚/看/月亮',   en: 'The fish looks at the moon',  pic: '🐟🌙', lv: 1 },
    { ch: '雞在跳舞', seg: '雞/在/跳舞',   en: 'The chicken is dancing',      pic: '🐔💃', lv: 1 },
    { ch: '下雪了', seg: '下雪/了',     en: 'It is snowing',               pic: '🌨️❄️', lv: 1 },
    { ch: '月亮笑了', seg: '月亮/笑/了',   en: 'The moon is smiling',         pic: '🌙😊', lv: 1 },
    /* level 2 — a little longer */
    { ch: '恐龍打籃球', seg: '恐龍/打/籃球', en: 'The dinosaur plays basketball', pic: '🦖🏀', lv: 2 },
    { ch: '大象坐火車', seg: '大象/坐/火車', en: 'The elephant rides the train',  pic: '🐘🚂', lv: 2 },
    { ch: '獅子怕老鼠', seg: '獅子/怕/老鼠', en: 'The lion is scared of the mouse', pic: '🦁🐭', lv: 2 },
    { ch: '猴子開飛機', seg: '猴子/開/飛機', en: 'The monkey flies a plane',      pic: '🐵✈️', lv: 2 },
    { ch: '青蛙跳很高', seg: '青蛙/跳/很高', en: 'The frog jumps very high',      pic: '🐸⬆️', lv: 2 },
    { ch: '雪人喝熱茶', seg: '雪人/喝/熱茶', en: 'The snowman drinks hot tea',    pic: '⛄🍵', lv: 2 },
    { ch: '星星眨眼睛', seg: '星星/眨/眼睛', en: 'The stars are blinking',        pic: '🌟👀', lv: 2 },
    { ch: '烏龜跑得快', seg: '烏龜/跑得/快', en: 'The turtle runs fast',          pic: '🐢💨', lv: 2 },
    { ch: '小狗愛洗澡', seg: '小狗/愛/洗澡', en: 'The puppy loves baths',         pic: '🐶🛁', lv: 2 },
    { ch: '貓咪打電話', seg: '貓咪/打/電話', en: 'The kitty makes a phone call',  pic: '🐱📞', lv: 2 },
    { ch: '蜜蜂住城堡', seg: '蜜蜂/住/城堡', en: 'The bee lives in a castle',     pic: '🐝🏰', lv: 2 },
    { ch: '熊愛吃蜂蜜', seg: '熊/愛吃/蜂蜜', en: 'The bear loves honey',          pic: '🐻🍯', lv: 2 },
    { ch: '鯊魚愛吃糖', seg: '鯊魚/愛吃/糖', en: 'The shark loves candy',         pic: '🦈🍬', lv: 2 },
    { ch: '恐龍愛蛋糕', seg: '恐龍/愛/蛋糕', en: 'The dinosaur loves cake',       pic: '🦖🍰', lv: 2 },
    { ch: '猴子吃香蕉', seg: '猴子/吃/香蕉', en: 'The monkey eats a banana',      pic: '🐵🍌', lv: 2 },
    { ch: '老鼠愛起司', seg: '老鼠/愛/起司', en: 'The mouse loves cheese',        pic: '🐭🧀', lv: 2 },
    { ch: '青蛙拿雨傘', seg: '青蛙/拿/雨傘', en: 'The frog holds an umbrella',    pic: '🐸☂️', lv: 2 },
    { ch: '小豬蓋房子', seg: '小豬/蓋/房子', en: 'The little pig builds a house', pic: '🐷🏠', lv: 2 },
    { ch: '鯨魚噴水', seg: '鯨魚/噴/水',   en: 'The whale spouts water',        pic: '🐳⛲', lv: 2 },
    { ch: '貓頭鷹看書', seg: '貓頭鷹/看書', en: 'The owl reads a book',          pic: '🦉📖', lv: 2 },
    { ch: '小鳥住樹上', seg: '小鳥/住/樹上', en: 'The bird lives in a tree',      pic: '🐦🌳', lv: 2 },
    { ch: '蝸牛慢慢走', seg: '蝸牛/慢慢/走', en: 'The snail walks slowly',        pic: '🐌⏰', lv: 2 },
    { ch: '雪人怕太陽', seg: '雪人/怕/太陽', en: 'The snowman fears the sun',     pic: '⛄☀️', lv: 2 },
    { ch: '星星愛月亮', seg: '星星/愛/月亮', en: 'The star loves the moon',       pic: '🌟🌙', lv: 2 },
    { ch: '恐龍騎馬', seg: '恐龍/騎/馬',   en: 'The dinosaur rides a horse',    pic: '🦖🐴', lv: 2 },
    { ch: '鬼怕黑', seg: '鬼/怕/黑',     en: 'The ghost is scared of the dark', pic: '👻🌑', lv: 2 },
    { ch: '蛋糕飛走了', seg: '蛋糕/飛走/了', en: 'The cake flew away',            pic: '🎂🎈', lv: 2 },
    { ch: '貓咪坐火箭', seg: '貓咪/坐/火箭', en: 'The kitty rides a rocket',      pic: '🐱🚀', lv: 2 },
    { ch: '恐龍上學去', seg: '恐龍/上學/去', en: 'The dinosaur goes to school',   pic: '🦖🎒', lv: 2 },
    { ch: '老虎喝汽水', seg: '老虎/喝/汽水', en: 'The tiger drinks soda',         pic: '🐯🥤', lv: 2 },
    { ch: '猴子戴眼鏡', seg: '猴子/戴/眼鏡', en: 'The monkey wears glasses',      pic: '🐵👓', lv: 2 },
    /* level 3 — the silliest ones */
    { ch: '章魚穿八隻鞋', seg: '章魚/穿/八隻/鞋', en: 'The octopus wears eight shoes',  pic: '🐙👟', lv: 3 },
    { ch: '企鵝去海邊玩', seg: '企鵝/去/海邊/玩', en: 'The penguin goes to the beach',  pic: '🐧🏖️', lv: 3 },
    { ch: '月亮吃了餅乾', seg: '月亮/吃了/餅乾', en: 'The moon ate a cookie',          pic: '🌙🍪', lv: 3 },
    { ch: '太陽戴墨鏡', seg: '太陽/戴/墨鏡',   en: 'The sun wears sunglasses',       pic: '☀️🕶️', lv: 3 },
    { ch: '恐龍害怕打針', seg: '恐龍/害怕/打針', en: 'The dinosaur is scared of shots', pic: '🦖💉', lv: 3 },
    { ch: '火箭飛到月亮', seg: '火箭/飛到/月亮', en: 'The rocket flies to the moon',   pic: '🚀🌕', lv: 3 },
    { ch: '小貓當國王', seg: '小貓/當/國王',   en: 'The kitten becomes king',        pic: '🐱👑', lv: 3 },
    { ch: '熊貓抱西瓜', seg: '熊貓/抱/西瓜',   en: 'The panda hugs a watermelon',    pic: '🐼🍉', lv: 3 },
    { ch: '機器人會唱歌', seg: '機器人/會/唱歌', en: 'The robot can sing',             pic: '🤖🎵', lv: 3 },
    { ch: '恐龍賣冰淇淋', seg: '恐龍/賣/冰淇淋', en: 'The dinosaur sells ice cream',   pic: '🦖🍦', lv: 3 },
    { ch: '聖誕老人游泳', seg: '聖誕老人/游泳', en: 'Santa goes swimming',            pic: '🎅🌊', lv: 3 },
    { ch: '青蛙王子唱歌', seg: '青蛙/王子/唱歌', en: 'The frog prince sings',          pic: '🐸👑', lv: 3 },
    { ch: '熊貓騎腳踏車', seg: '熊貓/騎/腳踏車', en: 'The panda rides a bike',         pic: '🐼🚲', lv: 3 },
    { ch: '兔子愛紅蘿蔔', seg: '兔子/愛/紅蘿蔔', en: 'The bunny loves carrots',        pic: '🐰🥕', lv: 3 },
    { ch: '螃蟹剪頭髮', seg: '螃蟹/剪/頭髮',   en: 'The crab gives haircuts',        pic: '🦀✂️', lv: 3 },
    { ch: '大象學溜冰', seg: '大象/學/溜冰',   en: 'The elephant learns to skate',   pic: '🐘⛸️', lv: 3 },
    { ch: '章魚彈鋼琴', seg: '章魚/彈/鋼琴',   en: 'The octopus plays the piano',    pic: '🐙🎹', lv: 3 },
    { ch: '獅子去剪頭髮', seg: '獅子/去/剪/頭髮', en: 'The lion gets a haircut',        pic: '🦁💈', lv: 3 },
    { ch: '企鵝愛吃冰', seg: '企鵝/愛吃/冰',   en: 'The penguin loves shaved ice',   pic: '🐧🍧', lv: 3 },
    { ch: '外星人來地球', seg: '外星人/來/地球', en: 'The alien visits Earth',         pic: '👽🌍', lv: 3 },
    { ch: '鞋子會走路', seg: '鞋子/會/走路',   en: 'The shoes walk by themselves',   pic: '👟👣', lv: 3 },
    { ch: '機器人吃電池', seg: '機器人/吃/電池', en: 'The robot eats batteries',       pic: '🤖🔋', lv: 3 },
    { ch: '恐龍打噴嚏', seg: '恐龍/打/噴嚏',   en: 'The dinosaur sneezes',           pic: '🦖🤧', lv: 3 },
    { ch: '大野狼吹氣球', seg: '大野狼/吹/氣球', en: 'The big bad wolf blows balloons', pic: '🐺🎈', lv: 3 },
    { ch: '恐龍學寫字', seg: '恐龍/學/寫字',   en: 'The dinosaur learns to write',   pic: '🦖✏️', lv: 3 },
    { ch: '螞蟻搬蛋糕', seg: '螞蟻/搬/蛋糕',   en: 'The ants carry a cake',          pic: '🐜🍰', lv: 3 },
    { ch: '火車鑽山洞', seg: '火車/鑽/山洞',   en: 'The train goes through the tunnel', pic: '🚂⛰️', lv: 3 }
  ];

  /* ---------- Character Builder: pieces that snap into a new character ----------
     layout: lr = side by side · tb = stacked · tri = one on top, two below
             wrap = the first piece hugs the second (門 around 口) */
  const BUILD = [
    /* level 1 */
    { parts: ['日', '月'], ch: '明', en: 'bright',  pic: '🔆', layout: 'lr', lv: 1 },
    { parts: ['木', '木'], ch: '林', en: 'woods',   pic: '🌲', layout: 'lr', lv: 1 },
    { parts: ['火', '火'], ch: '炎', en: 'blazing hot', pic: '🌡️', layout: 'tb', lv: 1 },
    { parts: ['月', '月'], ch: '朋', en: 'friend',  pic: '👫', layout: 'lr', lv: 1 },
    { parts: ['女', '子'], ch: '好', en: 'good',    pic: '👍', layout: 'lr', lv: 1 },
    { parts: ['一', '大'], ch: '天', en: 'sky',     pic: '🌈', layout: 'tb', lv: 1 },
    { parts: ['山', '山'], ch: '出', en: 'go out',  pic: '🏃', layout: 'tb', lv: 1 },
    /* level 2 */
    { parts: ['人', '木'], ch: '休', en: 'rest',    pic: '😴', layout: 'lr', lv: 2 },
    { parts: ['口', '鳥'], ch: '鳴', en: 'chirp',   pic: '🎵', layout: 'lr', lv: 2 },
    { parts: ['田', '力'], ch: '男', en: 'boy',     pic: '👦', layout: 'tb', lv: 2 },
    { parts: ['日', '一'], ch: '旦', en: 'dawn',    pic: '🌅', layout: 'tb', lv: 2 },
    { parts: ['小', '大'], ch: '尖', en: 'pointy',  pic: '📍', layout: 'tb', lv: 2 },
    { parts: ['田', '心'], ch: '思', en: 'think',   pic: '🤔', layout: 'tb', lv: 2 },
    { parts: ['門', '口'], ch: '問', en: 'ask',     pic: '❓', layout: 'wrap', lv: 2 },
    { parts: ['木', '子'], ch: '李', en: 'plum',    pic: '🍑', layout: 'tb', lv: 2 },
    { parts: ['十', '口'], ch: '古', en: 'ancient', pic: '🏺', layout: 'tb', lv: 2 },
    /* level 3 */
    { parts: ['木', '木', '木'], ch: '森', en: 'forest',  pic: '🏕️', layout: 'tri', lv: 3 },
    { parts: ['日', '日', '日'], ch: '晶', en: 'sparkle', pic: '✨', layout: 'tri', lv: 3 },
    { parts: ['口', '口', '口'], ch: '品', en: 'taste',   pic: '👅', layout: 'tri', lv: 3 },
    { parts: ['門', '耳'], ch: '聞', en: 'smell',   pic: '👃', layout: 'wrap', lv: 3 },
    { parts: ['白', '水'], ch: '泉', en: 'spring water', pic: '⛲', layout: 'tb', lv: 3 },
    { parts: ['山', '石'], ch: '岩', en: 'rock',    pic: '🗿', layout: 'tb', lv: 3 },
    { parts: ['人', '山'], ch: '仙', en: 'fairy',   pic: '🧚', layout: 'lr', lv: 3 },
    { parts: ['女', '馬'], ch: '媽', en: 'mom',     pic: '👩', layout: 'lr', lv: 3 },
    { parts: ['日', '生'], ch: '星', en: 'star',    pic: '⭐', layout: 'tb', lv: 3 },
    { parts: ['田', '土'], ch: '里', en: 'village', pic: '🏘️', layout: 'tb', lv: 3 }
  ];

  /* ---------- Spot the Twin: characters that look almost the same ---------- */
  const TWINS = [
    /* level 1 — easy to tell apart once you look */
    { a: '木', ae: 'tree',   b: '本', be: 'root',     lv: 1 },
    { a: '日', ae: 'sun',    b: '目', be: 'eye',      lv: 1 },
    { a: '大', ae: 'big',    b: '太', be: 'too much', lv: 1 },
    { a: '馬', ae: 'horse',  b: '鳥', be: 'bird',     lv: 1 },
    { a: '牛', ae: 'cow',    b: '午', be: 'noon',     lv: 1 },
    { a: '白', ae: 'white',  b: '百', be: 'hundred',  lv: 1 },
    { a: '十', ae: 'ten',    b: '千', be: 'thousand', lv: 1 },
    { a: '雨', ae: 'rain',   b: '兩', be: 'two of',   lv: 1 },
    /* level 2 — look closer */
    { a: '人', ae: 'person', b: '入', be: 'enter',    lv: 2 },
    { a: '土', ae: 'dirt',   b: '士', be: 'scholar',  lv: 2 },
    { a: '王', ae: 'king',   b: '玉', be: 'jade',     lv: 2 },
    { a: '天', ae: 'sky',    b: '夫', be: 'man',      lv: 2 },
    { a: '小', ae: 'small',  b: '少', be: 'few',      lv: 2 },
    { a: '田', ae: 'field',  b: '由', be: 'from',     lv: 2 },
    { a: '手', ae: 'hand',   b: '毛', be: 'fur',      lv: 2 },
    { a: '刀', ae: 'knife',  b: '力', be: 'strength', lv: 2 },
    /* level 3 — eagle eyes only */
    { a: '水', ae: 'water',  b: '永', be: 'forever',  lv: 3 },
    { a: '兔', ae: 'rabbit', b: '免', be: 'avoid',    lv: 3 },
    { a: '犬', ae: 'dog',    b: '大', be: 'big',      lv: 3 },
    { a: '見', ae: 'see',    b: '貝', be: 'shell',    lv: 3 },
    { a: '己', ae: 'self',   b: '已', be: 'already',  lv: 3 },
    { a: '末', ae: 'end',    b: '未', be: 'not yet',  lv: 3 },
    { a: '烏', ae: 'crow',   b: '鳥', be: 'bird',     lv: 3 },
    { a: '石', ae: 'stone',  b: '右', be: 'right',    lv: 3 }
  ];

  /* ---------- Opposites: learn words in pairs ---------- */
  const OPPOSITES = [
    { a: '大', b: '小', ae: 'big',  be: 'small', ap: '🐘', bp: '🐭', lv: 1 },
    { a: '上', b: '下', ae: 'up',   be: 'down',  ap: '⬆️', bp: '⬇️', lv: 1 },
    { a: '多', b: '少', ae: 'many', be: 'few',   ap: '🍎🍎🍎', bp: '🍎', lv: 1 },
    { a: '開', b: '關', ae: 'open', be: 'closed', ap: '🔓', bp: '🔒', lv: 1 },
    { a: '冷', b: '熱', ae: 'cold', be: 'hot',   ap: '🧊', bp: '🔥', lv: 1 },
    { a: '白', b: '黑', ae: 'white', be: 'black', ap: '⚪', bp: '⚫', lv: 1 },
    { a: '哭', b: '笑', ae: 'cry',  be: 'laugh', ap: '😭', bp: '😂', lv: 1 },
    { a: '日', b: '夜', ae: 'day',  be: 'night', ap: '☀️', bp: '🌙', lv: 1 },
    { a: '左', b: '右', ae: 'left', be: 'right', ap: '⬅️', bp: '➡️', lv: 2 },
    { a: '高', b: '低', ae: 'high', be: 'low',   ap: '🦒', bp: '🐢', lv: 2 },
    { a: '長', b: '短', ae: 'long', be: 'short', ap: '📏', bp: '✂️', lv: 2 },
    { a: '快', b: '慢', ae: 'fast', be: 'slow',  ap: '🐇', bp: '🐌', lv: 2 },
    { a: '男', b: '女', ae: 'boy',  be: 'girl',  ap: '👦', bp: '👧', lv: 2 },
    { a: '早', b: '晚', ae: 'morning', be: 'evening', ap: '🌅', bp: '🌃', lv: 2 },
    { a: '好', b: '壞', ae: 'good', be: 'bad',   ap: '👍', bp: '👎', lv: 2 },
    { a: '天', b: '地', ae: 'sky',  be: 'ground', ap: '🌈', bp: '🌍', lv: 2 },
    { a: '來', b: '去', ae: 'come', be: 'go',    ap: '🏠', bp: '🚶', lv: 3 },
    { a: '新', b: '舊', ae: 'new',  be: 'old',   ap: '✨', bp: '🪵', lv: 3 },
    { a: '輕', b: '重', ae: 'light', be: 'heavy', ap: '🪶', bp: '🪨', lv: 3 },
    { a: '乾', b: '濕', ae: 'dry',  be: 'wet',   ap: '☀️', bp: '💧', lv: 3 },
    { a: '進', b: '出', ae: 'go in', be: 'go out', ap: '📥', bp: '📤', lv: 3 },
    { a: '胖', b: '瘦', ae: 'fat',  be: 'thin',  ap: '🐷', bp: '🦴', lv: 3 },
    { a: '遠', b: '近', ae: 'far',  be: 'near',  ap: '🔭', bp: '🔍', lv: 3 },
    { a: '前', b: '後', ae: 'front', be: 'back', ap: '🚗', bp: '🚌', lv: 3 }
  ];

  /* ---------- Count & Say: things and their measure words ---------- */
  const COUNT = [
    { ch: '貓', en: 'cat',    pic: '🐱', m: '隻', lv: 1 },
    { ch: '狗', en: 'dog',    pic: '🐶', m: '隻', lv: 1 },
    { ch: '鳥', en: 'bird',   pic: '🐦', m: '隻', lv: 1 },
    { ch: '魚', en: 'fish',   pic: '🐟', m: '條', lv: 1 },
    { ch: '書', en: 'book',   pic: '📖', m: '本', lv: 1 },
    { ch: '花', en: 'flower', pic: '🌸', m: '朵', lv: 1 },
    { ch: '球', en: 'ball',   pic: '⚽', m: '顆', lv: 1 },
    { ch: '人', en: 'person', pic: '🚶', m: '個', lv: 1 },
    { ch: '蛇', en: 'snake',  pic: '🐍', m: '條', lv: 2 },
    { ch: '車', en: 'car',    pic: '🚗', m: '輛', lv: 2 },
    { ch: '蛋', en: 'egg',    pic: '🥚', m: '顆', lv: 2 },
    { ch: '星', en: 'star',   pic: '⭐', m: '顆', lv: 2 },
    { ch: '雲', en: 'cloud',  pic: '☁️', m: '朵', lv: 2 },
    { ch: '樹', en: 'tree',   pic: '🌳', m: '棵', lv: 2 },
    { ch: '筆', en: 'pen',    pic: '✏️', m: '枝', lv: 3 },
    { ch: '馬', en: 'horse',  pic: '🐴', m: '匹', lv: 3 },
    { ch: '茶', en: 'tea',    pic: '🍵', m: '杯', lv: 3 },
    { ch: '傘', en: 'umbrella', pic: '☂️', m: '把', lv: 3 },
    { ch: '船', en: 'boat',   pic: '⛵', m: '艘', lv: 3 },
    { ch: '門', en: 'door',   pic: '🚪', m: '扇', lv: 3 }
  ];
  const NUMBERS = ['', '一', '兩', '三', '四', '五', '六', '七', '八', '九'];
  const NUM_EN = ['', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine'];

  const byCh = {};
  WORDS.forEach(w => { byCh[w.ch] = w; });
  function word(ch) { return byCh[ch] || null; }
  function sameSound(a, b) { return HOMOPHONES.some(g => g.indexOf(a) >= 0 && g.indexOf(b) >= 0); }

  return { WORDS, WORDS2, SENTS, BUILD, TWINS, OPPOSITES, COUNT, NUMBERS, NUM_EN, HOMOPHONES, word, sameSound };
})();
